language: php

php:
#  - 5.5
#  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install

script:
  - phpunit --bootstrap tests/bootstrap.php.dist tests/FingerprintTest.php --coverage-text